image: jimyoshida/node-make-extra

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - cd website
  - yarn install
  - make usr
  - make
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - cd website
  - yarn install
  - make usr
  - make
  - mv ./build ../public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
